# Generated by Django 5.2.1 on 2025-05-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_rename_user_profile_player_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expInLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='expToNext',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='loginExpGainDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='progressPercent',
            field=models.FloatField(default=0.0),
        ),
    ]
