# Generated by Django 5.2.1 on 2025-05-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slogan',
            field=models.CharField(blank=True, default='在基地深處，訊號永不熄滅，識別者並未在此留下痕跡', max_length=200),
        ),
    ]
