# Generated by Django 5.2.1 on 2025-05-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_profile_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='articleExpGainDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='draftExpGainDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='likeExpGainDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='messageExpGainDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
