# Generated by Django 5.2.1 on 2025-05-27 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_profile_articleexpgaindate_profile_draftexpgaindate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
