# Generated by Django 5.2.1 on 2025-05-31 03:28

import player.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_alter_profile_birthday_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backgroundPhoto',
            field=models.ImageField(blank=True, null=True, upload_to=player.models.user_photo_path),
        ),
    ]
