# Generated by Django 5.2.1 on 2025-06-07 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
