# Generated by Django 5.2.1 on 2025-06-08 02:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastSeen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
