# Generated by Django 5.2.1 on 2025-06-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0013_profile_lastseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comment_visibility',
            field=models.CharField(choices=[('public', '公開'), ('fans', '僅限粉絲'), ('private', '私人')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='followers_visibility',
            field=models.CharField(choices=[('public', '公開'), ('fans', '僅限粉絲'), ('private', '私人')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='following_visibility',
            field=models.CharField(choices=[('public', '公開'), ('fans', '僅限粉絲'), ('private', '私人')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='like_visibility',
            field=models.CharField(choices=[('public', '公開'), ('fans', '僅限粉絲'), ('private', '私人')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='post_visibility',
            field=models.CharField(choices=[('public', '公開'), ('fans', '僅限粉絲'), ('private', '私人')], default='public', max_length=10),
        ),
    ]
