# Generated by Django 5.2.1 on 2025-05-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_lastedit_alter_article_section_delete_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('deleted', '已刪除草稿'), ('pending', '待審核'), ('rejected', '已退回'), ('published', '已發布'), ('removed', '已刪除文章')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(null=True),
        ),
    ]
