# Generated by Django 5.2.1 on 2025-05-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_comment_article_like_article_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
