# Generated by Django 5.2.1 on 2025-05-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_article_createat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='popularity',
            new_name='hot',
        ),
    ]
