# Generated by Django 5.2.1 on 2025-05-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_rename_popularity_article_hot'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publishAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
