# Generated by Django 5.2.1 on 2025-05-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_article_publishat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('deleted', '已刪除草稿'), ('pending', '待審核'), ('rejected', '已退回'), ('published', '已發布'), ('removed', '已刪除文章')], default='articles', max_length=10),
        ),
    ]
