# Generated by Django 5.2.1 on 2025-05-30 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_alter_article_author_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parentComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='article.comment'),
        ),
    ]
