# Generated by Django 5.2.1 on 2025-05-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_comment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='floor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
