# Generated by Django 5.2.1 on 2025-06-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_alter_like_unique_together_like_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='contentType',
        ),
        migrations.RemoveField(
            model_name='like',
            name='objectId',
        ),
    ]
