# Generated by Django 5.2.1 on 2025-06-06 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_remove_like_contenttype_remove_like_objectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='article.article'),
            preserve_default=False,
        ),
    ]
