# Generated by Django 5.2.1 on 2025-05-22 03:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slogan', models.CharField(blank=True, default='', max_length=160)),
                ('yesterday_posts', models.IntegerField(default=0)),
                ('yesterday_hot', models.FloatField(default=0)),
                ('total_posts', models.IntegerField(default=0)),
                ('total_hot', models.FloatField(default=0)),
            ],
        ),
    ]
