# Generated by Django 5.2.1 on 2025-05-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='total_hot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='yesterday_hot',
            field=models.IntegerField(default=0),
        ),
    ]
