# Generated by Django 5.2.1 on 2025-05-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_section_total_hot_alter_section_yesterday_hot'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='section_icon'),
        ),
    ]
