# Generated by Django 5.2.1 on 2025-05-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_section_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='section_background'),
        ),
        migrations.AlterField(
            model_name='section',
            name='slogan',
            field=models.CharField(blank=True, default='\u3000', max_length=160),
        ),
    ]
