# Generated by Django 5.2.1 on 2025-05-25 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_section_background_alter_section_slogan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='total_hot',
            new_name='totalHot',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='total_posts',
            new_name='totalPosts',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='yesterday_hot',
            new_name='yesterdayHot',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='yesterday_posts',
            new_name='yesterdayPosts',
        ),
    ]
