# Generated by Django 5.2.1 on 2025-05-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_rename_created_at_section_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='platform',
            field=models.CharField(choices=[('PC', '電腦遊戲'), ('Console', '家用主機遊戲'), ('Mobile', '手機遊戲'), ('Browser', '網頁遊戲'), ('Cloud', '雲端遊戲'), ('Arcade', '街機遊戲'), ('Handheld', '掌機遊戲'), ('VR', '虛擬實境遊戲')], default='PC', max_length=10),
        ),
    ]
